spring.application.name=quiz-participation-service

# Database Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Redis Configuration
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}

# Kafka Configuration
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.topics.submission=${KAFKA_SUBMISSION_TOPIC:quiz-submissions}

# Service URLs
services.quiz-service.url=${QUIZ_SERVICE_URL:http://localhost:8082}

# Server port
server.port=8080

# Outbox Relay Configuration
# Job runs every 10 seconds by default
outbox.relay.fixed-delay=${OUTBOX_RELAY_DELAY:30000}
outbox.relay.max-retries=${OUTBOX_RELAY_MAX_RETRIES:3}
outbox.relay.retry-window-hours=${OUTBOX_RELAY_RETRY_WINDOW:24}

# Logging
logging.level.com.ptit.soa2025=DEBUG
#logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

# CORS Configuration
spring.web.cors.allowed-origins=*
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=*
spring.web.cors.allow-credentials=true
spring.web.cors.max-age=3600